const MAP_CONTROLS_COPY =
  'Sleep om te bewegen\nKnijp, dubbeltik of gebruik het scrollwiel om te zoomen';
const HELICOPTER_CONTROLS_COPY =
  'Tik of klik om te vliegen\nHoud ingedrukt of sleep om te sturen\nRechtssleep, knijp, dubbeltik of gebruik het scrollwiel om te bewegen en zoomen';

export const PALETTE = Object.freeze({
  water: 0xf4f7fb,
  waterVector: 0x8dcdf4,
  land: 0xd8d8d8,
  landOverlay: 0xfaf8f3,
  landVector: 0x90be67,
  hydroFill: 0xe3f0f8,
  hydroFillVector: 0x74c2eb,
  hydroLine: 0x78abc7,
  hydroLineVector: 0x2f88b7,
  detailLand: 0xf3ead7,
  detailLandVector: 0x9ccc79,
  border: 0x444444,
  borderStrong: 0x253140,
  borderVector: 0x30492d,
  detailBorder: 0x41556c,
  detailBorderVector: 0x486344,
  marker: 0xff6b4a,
  markerRing: 0xffffff,
  reliefTint: 0xf3f7fa,
  reliefTintHighZoom: 0xdeebf2,
  overlayBackground: 'rgba(15, 23, 42, 0.72)',
  overlayText: '#f8fafc',
});

export const WORLD_LAYOUT = Object.freeze({
  WIDTH: 4096,
  HEIGHT: 2048,
});

export const WORLD_DEPTHS = Object.freeze({
  RELIEF: 0,
  MAP: 1,
  HYDRO_FILL: 1.6,
  HYDRO_LINE: 1.8,
  MAP_BORDER: 2,
  DETAIL_MAP: 2.5,
  MARKER: 3,
  QUIZ_TARGET: 4,
  HELICOPTER: 5,
  OVERLAY: 10,
});

export const CAMERA_LIMITS = Object.freeze({
  MAX_ZOOM: 1200,
  WHEEL_ZOOM_SPEED: 0.0015,
  DOUBLE_TAP_DELAY: 280,
  DOUBLE_TAP_DISTANCE: 28,
  DOUBLE_TAP_ZOOM_FACTOR: 1.6,
});

export const CAMERA_FOLLOW = Object.freeze({
  FOLLOW_LAG: 0.12,
  FOLLOW_LERP: 0.12,
  DEADZONE_WIDTH: 160,
  DEADZONE_HEIGHT: 120,
  INPUT_GRACE_MS: 3000,
  ZOOM_GRACE_MS: 500,
});

export const MARKER_STYLE = Object.freeze({
  RADIUS: 8,
  STROKE_WIDTH: 3,
  ALPHA: 0.95,
  MIN_SCALE: 0.12,
  MAX_SCALE: 6,
  DEPTH: WORLD_DEPTHS.MARKER,
});

export const HELICOPTER_STYLE = Object.freeze({
  DEPTH: WORLD_DEPTHS.HELICOPTER,
  REFERENCE_SCREEN_WIDTH: 64,
  MIN_SCREEN_WIDTH_FACTOR: 0.22,
  MAX_SCREEN_WIDTH_FACTOR: 0.56,
  ZOOM_GROWTH_MULTIPLIER: 12,
  ZOOM_GROWTH_CURVE: 0.85,
  MIN_SCALE: 0.0005,
  MAX_SCALE: 4,
});

export const QUIZ_TARGET_STYLE = Object.freeze({
  SCREEN_RADIUS: 14,
  RING_STROKE: 2.5,
  PROGRESS_STROKE: 5.5,
  REVEAL_DURATION_MS: 2200,
  REVEAL_CITY_RADIUS: 18,
  REVEAL_AREA_RADIUS: 26,
  REVEAL_WATER_RADIUS: 30,
  REVEAL_LINE_WIDTH: 4,
  REVEAL_BORDER_WIDTH: 2.4,
});

export const MOVEMENT_STYLE = Object.freeze({
  MAX_SPEED: 420,
  ACCELERATION: 880,
  DECELERATION_RADIUS: 320,
  STOP_THRESHOLD: 18,
});

export const ROTATION_STYLE = Object.freeze({
  TURN_SPEED: 7,
  MIN_SPEED: 10,
});

export const MAP_STYLE = Object.freeze({
  RELIEF_ALPHA: 0.88,
  RELIEF_MIN_ALPHA: 0.18,
  RELIEF_BACKGROUND_ALPHA: 0.15,
  RELIEF_FADE_START_MULTIPLIER: 7,
  RELIEF_FADE_END_MULTIPLIER: 26,
  UNAVAILABLE_REGION_ALPHA: 0.3,
  LAND_ALPHA: 0.18,
  LAND_HIGH_ZOOM_ALPHA: 0.38,
  LAND_VECTOR_ALPHA: 0.82,
  LAND_EMPHASIS_START_MULTIPLIER: 5,
  LAND_EMPHASIS_END_MULTIPLIER: 16,
  BORDER_ALPHA: 0.74,
  BORDER_HIGH_ZOOM_ALPHA: 1,
  BORDER_SCREEN_WIDTH: 1,
  BORDER_EMPHASIS_SCREEN_WIDTH: 1.2,
  BORDER_EMPHASIS_START_MULTIPLIER: 4.5,
  BORDER_EMPHASIS_END_MULTIPLIER: 12,
  GEOJSON_SIMPLIFY_TOLERANCE: 0.005,
  HYDRO_FILL_ALPHA: 0.18,
  HYDRO_FILL_HIGH_ZOOM_ALPHA: 0.78,
  HYDRO_FILL_START_MULTIPLIER: 4.5,
  HYDRO_FILL_FULL_MULTIPLIER: 11,
  HYDRO_FILL_GEOJSON_SIMPLIFY_TOLERANCE: 0.0012,
  HYDRO_LINE_ALPHA: 0.14,
  HYDRO_LINE_HIGH_ZOOM_ALPHA: 0.72,
  HYDRO_LINE_SCREEN_WIDTH: 0.7,
  HYDRO_LINE_EMPHASIS_SCREEN_WIDTH: 1.9,
  HYDRO_LINE_START_MULTIPLIER: 6.5,
  HYDRO_LINE_FULL_MULTIPLIER: 15,
  HYDRO_LINE_GEOJSON_SIMPLIFY_TOLERANCE: 0.0016,
  DETAIL_FILL_ALPHA: 0.24,
  DETAIL_FILL_HIGH_ZOOM_ALPHA: 0.34,
  DETAIL_BORDER_ALPHA: 0.94,
  DETAIL_BORDER_HIGH_ZOOM_ALPHA: 1,
  DETAIL_BORDER_SCREEN_WIDTH: 0.9,
  DETAIL_BORDER_EMPHASIS_SCREEN_WIDTH: 1.05,
  DETAIL_START_MULTIPLIER: 7,
  DETAIL_FULL_MULTIPLIER: 20,
  DETAIL_GEOJSON_SIMPLIFY_TOLERANCE: 0.0018,
  VECTOR_COLOR_START_MULTIPLIER: 12,
  VECTOR_COLOR_END_MULTIPLIER: 28,
});

export const OVERLAY_STYLE = Object.freeze({
  PADDING: 16,
  MAX_WIDTH: 320,
  FONT_FAMILY:
    'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  FONT_SIZE: '14px',
  LINE_SPACING: 4,
});

export const UI_COPY = Object.freeze({
  CONTROLS: MAP_CONTROLS_COPY,
  MAP_CONTROLS: MAP_CONTROLS_COPY,
  HELICOPTER_CONTROLS: HELICOPTER_CONTROLS_COPY,
});
